import{a as b,S as L,i as a}from"./assets/vendor-BSTwZ_tR.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))n(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const l of s.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&n(l)}).observe(document,{childList:!0,subtree:!0});function e(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function n(t){if(t.ep)return;t.ep=!0;const s=e(t);fetch(t.href,s)}})();const w="https://pixabay.com/api/",v="52544403-d4b110e344dc82246161e65d0";let u=1,S=15;async function d(o,r=!1){r&&(u=1);try{const e=await b.get(w,{params:{key:v,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:u,per_page:S}}),{hits:n,totalHits:t}=e.data;return u+=1,{hits:n,totalHits:t}}catch(e){return console.error("Sorry, there are no images matching your search query. Please try again!",e),{hits:[],totalHits:0}}}const h=document.querySelector(".gallery"),y=document.querySelector(".loader"),f=document.querySelector(".btn"),q=new L(".gallery a",{captionsData:"alt",captionsDelay:250});function p(o){const r=o.map(e=>`
    <li class="gallery-item">
  <a href="${e.largeImageURL}" target="_blank">
     <img
       src="${e.webformatURL}"
      alt="${e.tags}" loading="lazy"
    />
  </a>
  <div class="info">
  <p><b>Likes:</b> ${e.likes}</p>
  <p><b>Views:</b> ${e.views}</p>
  <p><b>Comments:</b> ${e.comments}</p>
  <p><b>Downloads:</b> ${e.downloads}</p>   
  </div>
</li>`).join("");h.insertAdjacentHTML("beforeend",r),q.refresh()}function R(){h.innerHTML=""}function g(){y.classList.remove("hidden")}function i(){y.classList.add("hidden")}function P(){f.classList.remove("hidden-load")}function c(){f.classList.add("hidden-load")}const B=document.querySelector(".form"),$=document.querySelector(".form input"),H=document.querySelector(".btn");let m="";B.addEventListener("submit",async o=>{o.preventDefault();const r=$.value.trim();if(!r){a.warning({title:"Warning",message:"Please enter a search query!",position:"topRight"});return}m=r,c(),R(),g();try{const{hits:e,totalHits:n}=await d(r,!0);if(i(),e.length===0){a.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",class:"my-toast"});return}p(e),e.length>=n?(a.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}),c()):P()}catch(e){i(),console.error(e),a.error({title:"Error",message:"Something went wrong while fetching images!",position:"topRight"})}});H.addEventListener("click",async()=>{g();try{const{hits:o,totalHits:r}=await d(m);if(i(),o.length===0){c(),a.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"});return}p(o);const e=document.querySelector(".gallery-item");if(e){const t=e.getBoundingClientRect().height;window.scrollBy({top:t*2,behavior:"smooth"})}document.querySelectorAll(".gallery-item").length>=r&&(c(),a.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch(o){i(),console.error(o)}});
//# sourceMappingURL=index.js.map
